all:
	g++ -std=c++11 src/*.cpp -o exec

run:
	./exec bpinstances/da-BPWC_1_9_9.txt solucao/da-BPWC_1_9_9.txt
	./exec bpinstances/da-BPWC_2_5_8.txt solucao/da-BPWC_2_5_8.txt
	./exec bpinstances/da-BPWC_3_1_1.txt solucao/da-BPWC_3_1_1.txt
	./exec bpinstances/da-BPWC_3_8_5.txt solucao/da-BPWC_3_8_5.txt
	./exec bpinstances/da-BPWC_4_2_8.txt solucao/da-BPWC_4_2_8.txt
	./exec bpinstances/d-BPWC_2_2_5.txt solucao/d-BPWC_2_2_5.txt
	./exec bpinstances/d-BPWC_2_3_1.txt solucao/d-BPWC_2_3_1.txt
	./exec bpinstances/d-BPWC_2_8_5.txt solucao/d-BPWC_2_8_5.txt
	./exec bpinstances/d-BPWC_3_5_3.txt solucao/d-BPWC_3_5_3.txt
	./exec bpinstances/d-BPWC_3_6_2.txt solucao/d-BPWC_3_6_2.txt
	./exec bpinstances/d-BPWC_3_6_6.txt solucao/d-BPWC_3_6_6.txt
	./exec bpinstances/d-BPWC_3_6_9.txt solucao/d-BPWC_3_6_9.txt
	./exec bpinstances/d-BPWC_3_7_7.txt solucao/d-BPWC_3_7_7.txt
	./exec bpinstances/d-BPWC_4_2_5.txt solucao/d-BPWC_4_2_5.txt
	./exec bpinstances/d-BPWC_4_5_6.txt solucao/d-BPWC_4_5_6.txt
	./exec bpinstances/d-BPWC_4_7_8.txt solucao/d-BPWC_4_7_8.txt
	./exec bpinstances/ta-BPWC_5_4_10.txt solucao/ta-BPWC_5_4_10.txt
	./exec bpinstances/ta-BPWC_5_7_3.txt solucao/ta-BPWC_5_7_3.txt
	./exec bpinstances/ta-BPWC_6_7_5.txt solucao/ta-BPWC_6_7_5.txt
	./exec bpinstances/ta-BPWC_7_9_7.txt solucao/ta-BPWC_7_9_7.txt
	./exec bpinstances/ta-BPWC_8_7_7.txt solucao/ta-BPWC_8_7_7.txt
	./exec bpinstances/tELGN-BPWC_5_9_19.txt solucao/tELGN-BPWC_5_9_19.txt
	./exec bpinstances/tELGN-BPWC_6_4_16.txt solucao/tELGN-BPWC_6_4_16.txt
	./exec bpinstances/tELGN-BPWC_6_6_19.txt solucao/tELGN-BPWC_6_6_19.txt
	./exec bpinstances/tELGN-BPWC_7_1_18.txt solucao/tELGN-BPWC_7_1_18.txt
	./exec bpinstances/tELGN-BPWC_7_2_2.txt solucao/tELGN-BPWC_7_2_2.txt
	./exec bpinstances/tELGN-BPWC_7_6_10.txt solucao/tELGN-BPWC_7_6_10.txt
	./exec bpinstances/tELGN-BPWC_7_8_3.txt solucao/tELGN-BPWC_7_8_3.txt
	./exec bpinstances/tELGN-BPWC_7_9_5.txt solucao/tELGN-BPWC_7_9_5.txt
	./exec bpinstances/tMIMT-BPPC_5_3_1.txt solucao/tMIMT-BPPC_5_3_1.txt
	./exec bpinstances/tMIMT-BPPC_5_4_7.txt solucao/tMIMT-BPPC_5_4_7.txt
	./exec bpinstances/tMIMT-BPPC_5_5_4.txt solucao/tMIMT-BPPC_5_5_4.txt
	./exec bpinstances/tMIMT-BPPC_6_2_2.txt solucao/tMIMT-BPPC_6_2_2.txt
	./exec bpinstances/tMIMT-BPPC_7_1_5.txt solucao/tMIMT-BPPC_7_1_5.txt
	./exec bpinstances/tMIMT-BPPC_7_8_3.txt solucao/tMIMT-BPPC_7_8_3.txt
	./exec bpinstances/tMIMT-BPPC_8_6_7.txt solucao/tMIMT-BPPC_8_6_7.txt
	./exec bpinstances/ua-BPWC_1_5_2.txt solucao/ua-BPWC_1_5_2.txt
	./exec bpinstances/ua-BPWC_4_2_9.txt solucao/ua-BPWC_4_2_9.txt
	./exec bpinstances/ua-BPWC_4_5_4.txt solucao/ua-BPWC_4_5_4.txt
	./exec bpinstances/ua-BPWC_4_7_5.txt solucao/ua-BPWC_4_7_5.txt
	./exec bpinstances/ua-BPWC_4_8_9.txt solucao/ua-BPWC_4_8_9.txt
	./exec bpinstances/uELGN-BPWC_1_2_1.txt solucao/uELGN-BPWC_1_2_1.txt
	./exec bpinstances/uELGN-BPWC_1_2_20.txt solucao/uELGN-BPWC_1_2_20.txt
	./exec bpinstances/uELGN-BPWC_1_5_1.txt solucao/uELGN-BPWC_1_5_1.txt
	./exec bpinstances/uELGN-BPWC_1_7_10.txt solucao/uELGN-BPWC_1_7_10.txt
	./exec bpinstances/uELGN-BPWC_2_4_7.txt solucao/uELGN-BPWC_2_4_7.txt
	./exec bpinstances/uELGN-BPWC_2_7_16.txt solucao/uELGN-BPWC_2_7_16.txt
	./exec bpinstances/uELGN-BPWC_3_1_18.txt solucao/uELGN-BPWC_3_1_18.txt
	./exec bpinstances/uELGN-BPWC_3_3_9.txt solucao/uELGN-BPWC_3_3_9.txt
	./exec bpinstances/uELGN-BPWC_3_3_18.txt solucao/uELGN-BPWC_3_3_18.txt
